# dotnet build

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  testProject: './src/test/Minsk.Test/Minsk.Test.csproj'

steps:

- script: dotnet build --configuration $(buildConfiguration) --logger "trx;LogFileName=TestResults.xml"
  displayName: 'dotnet build --configuration $(buildConfiguration) --logger "trx;LogFileName=TestResults.xml"'
- script: dotnet test $(testProject)
  displayName: 'dotnet test $(testProject)'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: './src/test/Minsk.Test/TestResults/TestResults.xml'
    testRunTitle: 'Publish test results'
